apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-go-app-canary
  labels:
    app: my-go-app
    namespace: application
    environment: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-go-app
      environment: canary
  template:
    metadata:
      labels:
        app: my-go-app
        environment: canary
    spec:
      containers:
      - name: my-go-app
        image: trnimagestorage.azurecr.io/my-go-app:canary
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-go-app-canary
  namespace: application
spec:
  selector:
    app: my-go-app
    environment: canary
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
