apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-go-app
  namespace: default
  labels:
    app: my-go-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-go-app
  template:
    metadata:
      labels:
        app: my-go-app
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
      - name: my-go-app
        image: trnimagestorage.azurecr.io/my-go-app:v0.0.6
        ports:
        - containerPort: 8080
        resources:               # Add resource requests and limits here
          requests:
            cpu: "200m"          # Request 200 millicores of CPU
            memory: "256Mi"      # Request 256 MiB of memory
          limits:
            cpu: "500m"          # Limit to 500 millicores of CPU
            memory: "512Mi"      # Limit to 512 MiB of memory
---
apiVersion: v1
kind: Service
metadata:
  name: my-go-app
  namespace: default
spec:
  selector:
    app: my-go-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: web
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-go-app-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-go-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # Target CPU utilization percentage
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70  # Target Memory utilization percentage
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60  # Wait for 1 minute before scaling down
      policies:
      - type: Percent
        value: 10   # Decrease replicas by 10% per minute
        periodSeconds: 60
    scaleUp:
      policies:
      - type: Pods
        value: 4    # Increase replicas by 4 pods at a time
        periodSeconds: 15
      - type: Percent
        value: 100  # Or increase by 100% at a time
        periodSeconds: 15