apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-go-app
  labels:
    app: my-go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-go-app
  template:
    metadata:
      labels:
        app: my-go-app
    spec:
      containers:
      - name: my-go-app
        image: trnimagestorage.azurecr.io/my-go-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-go-app
spec:
  selector:
    app: my-go-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
