name: Check Pull Request Title

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - main

jobs:
  check-title:
    runs-on: ubuntu-latest

    steps:
      - name: Check Pull Request Title
        uses: actions/github-script@v6
        with:
          script: |
            const prTitle = context.payload.pull_request.title;
            const releasePattern = /^release\/v\d+\.\d+\.\d+$/;
            const hotfixPattern = /^hotfix\/.*/;
            if (!releasePattern.test(prTitle) && !hotfixPattern.test(prTitle)) {
              core.setFailed(`Pull request title "${prTitle}" does not match the required naming convention (release/vX.X.X or hotfix/*)`);
            }
