name: Check Pull Request Title

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check Branch Name
        uses: actions/github-script@v6
        with:
          script: |
            const branchName = context.payload.pull_request.head.ref;
            const releasePattern = /^release\/v\d+\.\d+\.\d+$/;
            const hotfixPattern = /^hotfix\/.*/;
            if (!releasePattern.test(branchName) && !hotfixPattern.test(branchName)) {
              core.setFailed(`Branch name "${branchName}" does not match the required naming convention (release/vX.X.X or hotfix/*)`);
            }
