name: Deploy to ACR

on:
  pull_request:
    types: [closed]

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Container Registry Login
        run: |
          az acr login --name trnimagestorage

      - name: Build and push Docker image
        env:
          ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
        run: |
          IMAGE_TAG=latest
          docker build -t $ACR_LOGIN_SERVER/my-go-app:$IMAGE_TAG .
          docker push $ACR_LOGIN_SERVER/my-go-app:$IMAGE_TAG
